name: Build & Release Discord Cleaner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite app
        run: pnpm vite:build

      - name: Build Electron App
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pnpm electron:build:windows
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            pnpm electron:build:linux
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            pnpm electron:build:mac
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: discord-cleaner-${{ runner.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: discord-cleaner-windows
          path: dist/windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: discord-cleaner-ubuntu
          path: dist/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: discord-cleaner-macos
          path: dist/macos

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: Discord Cleaner Release v${{ github.run_number }}
          artifacts: |
            dist/windows/*
            dist/linux/*
            dist/macos/*
